CREATE TABLE t_category
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(50)                             NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(50),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN                                 NOT NULL,
    type               VARCHAR(255)                            NOT NULL,
    name               VARCHAR(255),
    description        VARCHAR(255),
    CONSTRAINT pk_t_category PRIMARY KEY (id)
);

CREATE TABLE t_product
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(50)                             NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(50),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN                                 NOT NULL,
    material_number    VARCHAR(10)                             NOT NULL,
    name               VARCHAR(255),
    description        VARCHAR(255),
    price              DOUBLE PRECISION,
    product_id         BIGINT,
    category_id        BIGINT,
    CONSTRAINT pk_t_product PRIMARY KEY (id)
);

CREATE TABLE t_user
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype              VARCHAR(31),
    created_by         VARCHAR(50)                             NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(50),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN                                 NOT NULL,
    first_name         VARCHAR(255),
    last_name          VARCHAR(255),
    email              VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_t_user PRIMARY KEY (id)
);

ALTER TABLE t_category
    ADD CONSTRAINT uc_t_category_type UNIQUE (type);

ALTER TABLE t_product
    ADD CONSTRAINT uc_t_product_materialnumber UNIQUE (material_number);

ALTER TABLE t_user
    ADD CONSTRAINT uc_t_user_email UNIQUE (email);

ALTER TABLE t_product
    ADD CONSTRAINT FK_T_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES t_category (id);

ALTER TABLE t_product
    ADD CONSTRAINT FK_T_PRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES t_user (id);
